version: '3.8'

services:
  transcription-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - .env.prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
